[pytest]
addopts = -v --disable-pytest-warnings -W ignore::DeprecationWarning -p no:cacheprovider

markers =
    smoke: Smoke test suite
    regression: Regression test suite
    sanity: Sanity test suite
    login: Login related tests
    products: Product related tests